version: '3.6'
services:

  app:
    build: .
    container_name: recipes-app
    command: rails server --port 3000 --binding 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
      - home:/home/app
    networks:
      - net
    depends_on:
      - db
      - cache
    env_file: .env
    tty: true
    stdin_open: true

  db:
    image: postgres:10.5
    container_name: recipes-db
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - net

  cache:
    image: redis
    container_name: recipes-cache
    ports:
      - 6379:6379
    networks:
      - net

  worker:
    build: .
    container_name: recipes-worker
    command: sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - cache
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
      - home:/home/app
    networks:
      - net
    depends_on:
      - db
      - cache
    env_file: .env
    tty: true
    stdin_open: true

volumes:
  database:
  cache:
  gems:
  home:

networks:
  net:
